package dao

var (
	ComSpecValue  *comSpecValue
	Com           *com
	User          *user
	Signin        *signin
	Order         *order
	Address       *address
	Freight       *freight
	ComSpec       *comSpec
	PointLimit    *pointLimit
	ComSku        *comSku
	Banner        *banner
	OrderLog      *orderLog
	OrderGoods    *orderGoods
	ComImage      *comImage
	AdminUser     *adminUser
	OrderExtend   *orderExtend
	AddressType   *addressType
	Attachment    *attachment
	Image         *image
	PointLog      *pointLog
	ComRelateCate *comRelateCate
	SigninLog     *signinLog
	ComStore      *comStore
	Comment       *comment
	UserGoods     *userGoods
	Cart          *cart
	AccessToken   *accessToken
	UserOpen      *userOpen
	ComCate       *comCate
	OrderPay      *orderPay
)
